all:
  hosts:
  children:
    prometheus:
      hosts:
        prom_server:
          ansible_connection: ssh
          ansible_port: 22
          ansible_host: 192.168.10.20
          ansible_user: vagrant
          ssh_key: /.ssh/vagrant

    node_exporter:
      hosts:
        s1:
          ansible_host: 192.168.10.21
        s2:
          ansible_host: 192.168.10.22
        s3:
          ansible_host: 192.168.10.24
      vars:
        ansible_connection: ssh
        ansible_port: 22
        ansible_user: vagrant
        ssh_key: /.ssh/vagrant   

    db_exporter:
      hosts:
        s1:
          ansible_host: 192.168.10.21
        s3:
          ansible_host: 192.168.10.24
      vars:
        ansible_connection: ssh
        ansible_port: 22
        ansible_user: vagrant
        ssh_key: /.ssh/vagrant




